name: "Get ratings"

on:
  workflow_dispatch:
  
jobs:
    update_ratings:
      name: "Update ratings"
      runs-on: "ubuntu-latest"
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: "fetch"
          run: |
            sudo apt-get install -y jq
            curl https://itunes.apple.com/lookup\?id\=1037992616\&country\=gb | jq '.results[0].userRatingCount, .results[0].averageUserRating' >> ratings
        - uses: stefanzweifel/git-auto-commit-action@v4
